/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabteste;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author guilu
 */
public class Classificado extends javax.swing.JFrame {

    /**
     * Creates new form Classificado
     */
    public Classificado() {
        initComponents();
        this.j1.setVisible(false);
        this.j2.setVisible(false);
        this.jButton1.setVisible(false);
        this.jButton2.setVisible(false);
        this.setSize(510, 340);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Nao = new javax.swing.JRadioButton();
        Sim = new javax.swing.JRadioButton();
        j1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        j2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Nao.setText("NAO");
        Nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NaoActionPerformed(evt);
            }
        });
        getContentPane().add(Nao);
        Nao.setBounds(350, 120, 50, 40);

        Sim.setText("SIM");
        Sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimActionPerformed(evt);
            }
        });
        getContentPane().add(Sim);
        Sim.setBounds(290, 120, 50, 40);

        j1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        j1.setForeground(new java.awt.Color(255, 255, 255));
        j1.setText("Equipe: ");
        getContentPane().add(j1);
        j1.setBounds(0, 200, 500, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Deseja escolher a equi-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 10, 500, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("pe automaticamente");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 60, 500, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("classificada ?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 110, 280, 50);

        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });
        getContentPane().add(j2);
        j2.setBounds(10, 250, 300, 40);

        jButton1.setText("Ver Equipes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 180, 260, 40);

        jButton2.setText("Adicionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 250, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabteste/WhatsApp Image 2017-09-12 at 23.25.53.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 510, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed

    }//GEN-LAST:event_j2ActionPerformed

    private void NaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NaoActionPerformed

        if (Tela2.Participantes.size() == 6) {
            TelaMataMata6 tm6 = new TelaMataMata6();
            tm6.setVisible(true);
            this.setVisible(false);
        } else if (Tela2.Participantes.size() == 7 || Tela2.Participantes.size() == 8) {
            TelaMataMata8 tm8 = new TelaMataMata8();
            tm8.setVisible(true);
            this.setVisible(false);
        } else if (Tela2.Participantes.size() > 8 && Tela2.Participantes.size() < 11) {
            TelaMataMata10 tm10 = new TelaMataMata10();
            tm10.setVisible(true);
            this.setVisible(false);
        } else if (Tela2.Participantes.size() > 10 && Tela2.Participantes.size() < 13) {
            TelaMataMata12p1 tm12 = new TelaMataMata12p1();
            tm12.setVisible(true);
            this.setVisible(false);
        } else if (Tela2.Participantes.size() > 12 && Tela2.Participantes.size() < 17) {
            TelaMataMata16 tm16 = new TelaMataMata16();
            tm16.setVisible(true);
            this.setVisible(false);
        } else {
            try {
                throw new InvalidParticipantsAmountException("Número inválido de participantes");
            } catch (InvalidParticipantsAmountException ex) {
                Logger.getLogger(Tela2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_NaoActionPerformed

    private void SimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimActionPerformed
        if (this.Sim.isSelected()) {
            this.j1.setVisible(true);
            this.j2.setVisible(true);
            this.jButton1.setVisible(true);
            this.jButton2.setVisible(true);
        }
    }//GEN-LAST:event_SimActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Vetor = "";
        for (int i = 0; i < Tela2.Participantes.size(); i++) {
            Vetor = Vetor + Tela2.Participantes.get(i) + ", ";
        }
        JOptionPane.showMessageDialog(this, "" + Vetor);

    }//GEN-LAST:event_jButton1ActionPerformed
    public String aux1;
    public String aux2;
    public String aux3;
    int i = 0;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (Tela2.Participantes.size() == 6) {
            if (i == 0) {
                aux1 = j2.getText();
                j2.setText("");
            }
            if (i == 1) {
                aux2 = j2.getText();
                j2.setText("");                   
            TelaMataMata6 tm6 = new TelaMataMata6(aux1, aux2);
            tm6.setVisible(true);
            this.setVisible(false);
            }
            i++;
        }
        if (Tela2.Participantes.size() == 7) {
            aux1 = j2.getText();
            j2.getText().equals("");
            TelaMataMata8 tm8 = new TelaMataMata8(aux1);
            tm8.setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Classificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Classificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Classificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Classificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Classificado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Nao;
    private javax.swing.JRadioButton Sim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel j1;
    private javax.swing.JTextField j2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
