/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabteste;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author solange
 */
public class TelaMataMata12p1 extends javax.swing.JFrame {

    /**
     * Creates new form TelaMataMata
     */
    public TelaMataMata12p1() {
        initComponents();
        this.setSize(520, 355);
        this.setNome();
    }

    public static ArrayList<String> classificados = new ArrayList();
    public int counter = 0;
    public static String ultimosColocados1, ultimosColocados2, ultimosColocados3, ultimosColocados4;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ja4 = new javax.swing.JLabel();
        ja8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fa4 = new javax.swing.JTextField();
        fb6 = new javax.swing.JTextField();
        ja7 = new javax.swing.JLabel();
        fa6 = new javax.swing.JTextField();
        fa3 = new javax.swing.JTextField();
        jb8 = new javax.swing.JLabel();
        ja3 = new javax.swing.JLabel();
        fa8 = new javax.swing.JTextField();
        fb5 = new javax.swing.JTextField();
        jb5 = new javax.swing.JLabel();
        fb7 = new javax.swing.JTextField();
        jb7 = new javax.swing.JLabel();
        fb8 = new javax.swing.JTextField();
        jb4 = new javax.swing.JLabel();
        fa1 = new javax.swing.JTextField();
        ja1 = new javax.swing.JLabel();
        fa2 = new javax.swing.JTextField();
        ja2 = new javax.swing.JLabel();
        fa5 = new javax.swing.JTextField();
        ja5 = new javax.swing.JLabel();
        ja6 = new javax.swing.JLabel();
        fa7 = new javax.swing.JTextField();
        jb2 = new javax.swing.JLabel();
        jb6 = new javax.swing.JLabel();
        jb1 = new javax.swing.JLabel();
        fb2 = new javax.swing.JTextField();
        fb4 = new javax.swing.JTextField();
        fb1 = new javax.swing.JTextField();
        jb3 = new javax.swing.JLabel();
        fb3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ja4.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        ja4.setForeground(new java.awt.Color(255, 255, 255));
        ja4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(ja4);
        ja4.setBounds(0, 260, 90, 20);

        ja8.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        ja8.setForeground(new java.awt.Color(255, 255, 255));
        ja8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(ja8);
        ja8.setBounds(400, 250, 90, 20);

        jLabel2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Fase de Entrada e Quartas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 370, 30);

        fa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fa4ActionPerformed(evt);
            }
        });
        getContentPane().add(fa4);
        fa4.setBounds(90, 250, 40, 30);
        getContentPane().add(fb6);
        fb6.setBounds(290, 130, 40, 30);

        ja7.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        ja7.setForeground(new java.awt.Color(255, 255, 255));
        ja7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(ja7);
        ja7.setBounds(400, 230, 90, 20);
        getContentPane().add(fa6);
        fa6.setBounds(360, 70, 40, 30);
        getContentPane().add(fa3);
        fa3.setBounds(90, 220, 40, 30);

        jb8.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jb8.setForeground(new java.awt.Color(204, 204, 0));
        jb8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jb8);
        jb8.setBounds(330, 200, 100, 20);

        ja3.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        ja3.setForeground(new java.awt.Color(255, 255, 255));
        ja3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(ja3);
        ja3.setBounds(0, 230, 90, 20);
        getContentPane().add(fa8);
        fa8.setBounds(360, 250, 40, 30);
        getContentPane().add(fb5);
        fb5.setBounds(290, 100, 40, 30);

        jb5.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jb5.setForeground(new java.awt.Color(255, 255, 255));
        jb5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jb5);
        jb5.setBounds(330, 110, 100, 20);

        fb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb7ActionPerformed(evt);
            }
        });
        getContentPane().add(fb7);
        fb7.setBounds(290, 170, 40, 30);

        jb7.setBackground(new java.awt.Color(255, 255, 255));
        jb7.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jb7.setForeground(new java.awt.Color(255, 255, 255));
        jb7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jb7);
        jb7.setBounds(330, 170, 100, 20);
        getContentPane().add(fb8);
        fb8.setBounds(290, 200, 40, 30);

        jb4.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jb4.setForeground(new java.awt.Color(204, 204, 0));
        jb4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jb4);
        jb4.setBounds(60, 200, 100, 20);
        getContentPane().add(fa1);
        fa1.setBounds(90, 50, 40, 20);

        ja1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        ja1.setForeground(new java.awt.Color(255, 255, 255));
        ja1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(ja1);
        ja1.setBounds(0, 50, 90, 20);
        getContentPane().add(fa2);
        fa2.setBounds(90, 70, 40, 20);

        ja2.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        ja2.setForeground(new java.awt.Color(255, 255, 255));
        ja2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(ja2);
        ja2.setBounds(0, 70, 90, 20);
        getContentPane().add(fa5);
        fa5.setBounds(360, 40, 40, 30);

        ja5.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        ja5.setForeground(new java.awt.Color(255, 255, 255));
        ja5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(ja5);
        ja5.setBounds(400, 50, 90, 20);

        ja6.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        ja6.setForeground(new java.awt.Color(255, 255, 255));
        ja6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(ja6);
        ja6.setBounds(400, 70, 90, 20);
        getContentPane().add(fa7);
        fa7.setBounds(360, 220, 40, 30);

        jb2.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jb2.setForeground(new java.awt.Color(204, 204, 0));
        jb2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jb2);
        jb2.setBounds(60, 140, 100, 20);

        jb6.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jb6.setForeground(new java.awt.Color(204, 204, 0));
        jb6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jb6);
        jb6.setBounds(330, 140, 100, 20);

        jb1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jb1.setForeground(new java.awt.Color(255, 255, 255));
        jb1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jb1);
        jb1.setBounds(60, 110, 100, 20);

        fb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb2ActionPerformed(evt);
            }
        });
        getContentPane().add(fb2);
        fb2.setBounds(160, 130, 40, 30);

        fb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb4ActionPerformed(evt);
            }
        });
        getContentPane().add(fb4);
        fb4.setBounds(160, 200, 40, 30);
        getContentPane().add(fb1);
        fb1.setBounds(160, 100, 40, 30);

        jb3.setBackground(new java.awt.Color(255, 255, 255));
        jb3.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jb3.setForeground(new java.awt.Color(255, 255, 255));
        jb3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jb3);
        jb3.setBounds(60, 170, 100, 20);
        getContentPane().add(fb3);
        fb3.setBounds(160, 170, 40, 30);

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 50, 110, 30);

        fundo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        fundo.setForeground(new java.awt.Color(255, 255, 255));
        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabteste/WhatsApp Image 2017-09-12 at 23.25.53.jpeg"))); // NOI18N
        fundo.setText("jLabel1");
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 500, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fb2ActionPerformed

    private void fb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fb4ActionPerformed

    private void fa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fa4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fa4ActionPerformed

    private void fb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fb7ActionPerformed
    public void setNome() {      
        if (Tela2.Participantes.size() == 10) {
            Sorteio s = new Sorteio();
            ja5.setText("BOT");
            ja7.setText("BOT");
            s.Sortear();
            ja1.setText(Tela2.Participantes.get(0));
            ja3.setText(Tela2.Participantes.get(1));
            ja4.setText(Tela2.Participantes.get(2));
            ja2.setText(Tela2.Participantes.get(3));;
            ja6.setText(Tela2.Participantes.get(4));
            jb7.setText(Tela2.Participantes.get(5));
            ja8.setText(Tela2.Participantes.get(6));
            jb1.setText(Tela2.Participantes.get(7));
            jb3.setText(Tela2.Participantes.get(8));
            jb5.setText(Tela2.Participantes.get(9));
        }
        
        if (Tela2.Participantes.size() == 11) {
            Sorteio s = new Sorteio();
            ja5.setText("BOT");
            s.Sortear();
            ja1.setText(Tela2.Participantes.get(0));
            ja3.setText(Tela2.Participantes.get(1));
            ja4.setText(Tela2.Participantes.get(2));
            ja2.setText(Tela2.Participantes.get(3));
            ja6.setText(Tela2.Participantes.get(4));
            ja7.setText(Tela2.Participantes.get(5));
            ja8.setText(Tela2.Participantes.get(6));
            jb1.setText(Tela2.Participantes.get(7));
            jb3.setText(Tela2.Participantes.get(8));
            jb5.setText(Tela2.Participantes.get(9));
            jb7.setText(Tela2.Participantes.get(10));

        }

        if (Tela2.Participantes.size() == 12) {
            Sorteio s = new Sorteio();
            s.Sortear();
            ja1.setText(Tela2.Participantes.get(0));
            ja3.setText(Tela2.Participantes.get(1));
            ja4.setText(Tela2.Participantes.get(2));
            ja2.setText(Tela2.Participantes.get(3));
            ja5.setText(Tela2.Participantes.get(4));
            ja6.setText(Tela2.Participantes.get(11));
            ja7.setText(Tela2.Participantes.get(5));
            ja8.setText(Tela2.Participantes.get(6));
            jb1.setText(Tela2.Participantes.get(7));
            jb3.setText(Tela2.Participantes.get(8));
            jb5.setText(Tela2.Participantes.get(9));
            jb7.setText(Tela2.Participantes.get(10));

        }

    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //-----------------------PARTE DE ENTRADA------------------------
        if (!fa1.getText().equals("") && !fa2.getText().equals("")) {
            int a1 = Integer.parseInt(fa1.getText());
            int a2 = Integer.parseInt(fa2.getText());
            if (a1 > a2) {
                jb2.setText(ja1.getText());
            } else if (a2 > a1) {
                jb2.setText(ja2.getText());
            }
        }

        //part2   
        if (!fa3.getText().equals("") && !fa4.getText().equals("")) {
            int a3 = Integer.parseInt(fa3.getText());
            int a4 = Integer.parseInt(fa4.getText());
            if (a3 > a4) {
                jb4.setText(ja3.getText());
            } else if (a4 > a3) {
                jb4.setText(ja4.getText());
            }
        }
        //part 3
        if (!fa5.getText().equals("") && !fa6.getText().equals("")) {
            int a5 = Integer.parseInt(fa5.getText());
            int a6 = Integer.parseInt(fa6.getText());
            if (a5 > a6) {
                jb6.setText(ja5.getText());
            } else if (a6 > a5) {
                jb6.setText(ja6.getText());
            }
        }
        //part4
        if (!fa7.getText().equals("") && !fa4.getText().equals("")) {
            int a7 = Integer.parseInt(fa3.getText());
            int a8 = Integer.parseInt(fa4.getText());
            if (a7 > a8) {
                jb8.setText(ja7.getText());
            } else if (a8 > a7) {
                jb8.setText(ja8.getText());
            }
        }
        Pilha pilha = new Pilha();

        int p3 = Integer.parseInt(fa1.getText());
        int p4 = Integer.parseInt(fa2.getText());
        if (p3 < p4) {
            pilha.empilhar(ja1.getText());
        } else if (p4 < p3) {
            pilha.empilhar(ja2.getText());
        }
        int p5 = Integer.parseInt(fa3.getText());
        int p6 = Integer.parseInt(fa4.getText());
        if (p5 < p6) {
            pilha.empilhar(ja3.getText());
        } else if (p6 < p5) {
            pilha.empilhar(ja4.getText());
        }
        int p7 = Integer.parseInt(fa5.getText());
        int p8 = Integer.parseInt(fa6.getText());
        if (p7 < p8) {
            pilha.empilhar(ja5.getText());
        } else if (p8 < p7) {
            pilha.empilhar(ja6.getText());
        }
        int p9 = Integer.parseInt(fa7.getText());
        int p10 = Integer.parseInt(fa8.getText());
        if (p9 < p10) {
            pilha.empilhar(ja7.getText());
        } else if (p10 < p9) {
            pilha.empilhar(ja8.getText());
        }
        try {
            ultimosColocados1 = (String) pilha.desempilhar();
        } catch (PilhaVaziaException ex) {
            Logger.getLogger(TelaMataMata6.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ultimosColocados2 = (String) pilha.desempilhar();
        } catch (PilhaVaziaException ex) {
            Logger.getLogger(TelaMataMata6.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ultimosColocados3 = (String) pilha.desempilhar();
        } catch (PilhaVaziaException ex) {
            Logger.getLogger(TelaMataMata6.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ultimosColocados4 = (String) pilha.desempilhar();
        } catch (PilhaVaziaException ex) {
            Logger.getLogger(TelaMataMata6.class.getName()).log(Level.SEVERE, null, ex);
        }
        //--------------------------SEGUNDA FASE-------------------------
        //part1
        if (!fb1.getText().equals("") && !fb2.getText().equals("")) {
            int b1 = Integer.parseInt(fb1.getText());
            int b2 = Integer.parseInt(fb2.getText());
            if (b1 > b2) {
                classificados.add(jb1.getText());
            } else if (b2 > b1) {
                classificados.add(jb2.getText());
            }
            counter += 1;
        }

        //part2
        if (!fb3.getText().equals("") && !fb4.getText().equals("")) {
            int b3 = Integer.parseInt(fb3.getText());
            int b4 = Integer.parseInt(fb4.getText());
            if (b3 > b4) {
                classificados.add(jb3.getText());
            } else if (b4 > b3) {
                classificados.add(jb4.getText());
            }
            counter += 1;
        }
        //part3
        if (!fb5.getText().equals("") && !fb6.getText().equals("")) {
            int b5 = Integer.parseInt(fb5.getText());
            int b6 = Integer.parseInt(fb6.getText());
            if (b5 > b6) {
                classificados.add(jb5.getText());
            } else if (b6 > b5) {
                classificados.add(jb6.getText());
            }
            counter += 1;
        }

        //part4
        if (!fb7.getText().equals("") && !fb8.getText().equals("")) {
            int b7 = Integer.parseInt(fb7.getText());
            int b8 = Integer.parseInt(fb8.getText());
            if (b7 > b8) {
                classificados.add(jb7.getText());
            } else if (b8 > b7) {
                classificados.add(jb8.getText());
            }
            counter += 1;
            if (counter == 4) {
                TelaMataMata12p2 tm12p2 = new TelaMataMata12p2();
                tm12p2.setVisible(true);
            } else if(counter != 4){
                JOptionPane.showMessageDialog(this, "Digite o resultado de todos os jogos antes de prosseguir");
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMataMata12p1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMataMata12p1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMataMata12p1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMataMata12p1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMataMata12p1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fa1;
    private javax.swing.JTextField fa2;
    private javax.swing.JTextField fa3;
    private javax.swing.JTextField fa4;
    private javax.swing.JTextField fa5;
    private javax.swing.JTextField fa6;
    private javax.swing.JTextField fa7;
    private javax.swing.JTextField fa8;
    private javax.swing.JTextField fb1;
    private javax.swing.JTextField fb2;
    private javax.swing.JTextField fb3;
    private javax.swing.JTextField fb4;
    private javax.swing.JTextField fb5;
    private javax.swing.JTextField fb6;
    private javax.swing.JTextField fb7;
    private javax.swing.JTextField fb8;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel ja1;
    private javax.swing.JLabel ja2;
    private javax.swing.JLabel ja3;
    private javax.swing.JLabel ja4;
    private javax.swing.JLabel ja5;
    private javax.swing.JLabel ja6;
    private javax.swing.JLabel ja7;
    private javax.swing.JLabel ja8;
    private javax.swing.JLabel jb1;
    private javax.swing.JLabel jb2;
    private javax.swing.JLabel jb3;
    private javax.swing.JLabel jb4;
    private javax.swing.JLabel jb5;
    private javax.swing.JLabel jb6;
    private javax.swing.JLabel jb7;
    private javax.swing.JLabel jb8;
    // End of variables declaration//GEN-END:variables
}
