  /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabteste;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author solange
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {

        try {
            this.setContentPane(new JLabel(new ImageIcon(ImageIO.read(new File("F:\\TRABALHODEVERDADEDEALP\\TrabTeste\\src\\trabteste\\WhatsApp Image 2017-09-12 at 23.24.28.jpeg")))));
        } catch (IOException e) {
            e.printStackTrace();
        }

        initComponents();
        this.setSize(510, 355);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotaoGerar = new javax.swing.JButton();
        BotaoSobre = new javax.swing.JButton();
        BotaoSugestao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 153));
        getContentPane().setLayout(null);

        BotaoGerar.setText("Gerar");
        BotaoGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGerarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoGerar);
        BotaoGerar.setBounds(210, 251, 70, 40);

        BotaoSobre.setText("Sobre");
        BotaoSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSobreActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoSobre);
        BotaoSobre.setBounds(370, 280, 61, 23);

        BotaoSugestao.setText("Sugestões");
        BotaoSugestao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSugestaoActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoSugestao);
        BotaoSugestao.setBounds(60, 270, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSobreActionPerformed
        // TODO add your handling code here:
        BotaoSobre.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ev) {
                JOptionPane.showMessageDialog(rootPane, "\"O programa desenvolvido por Rafael Roth e Guilherme "
                        + " Luiz tem o intuito de agilizar a formação de tabelas para"
                        + " torneios de qualquer modalidade\"");
            }
        });


    }//GEN-LAST:event_BotaoSobreActionPerformed

    private void BotaoGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGerarActionPerformed
        Tela2 tela2 = new Tela2();
        tela2.setVisible(true);
        
    }//GEN-LAST:event_BotaoGerarActionPerformed

    private void BotaoSugestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSugestaoActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Para o sistema de mata-mata, você pode"
                + " gerar tabelas com 6, 9, 12 ou 16 times. "
                + "Caso ocorra um empate, adicione o resuiltado dos pênaltis no dígito seguinte ao do resultado do jogo ");
    }//GEN-LAST:event_BotaoSugestaoActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoGerar;
    private javax.swing.JButton BotaoSobre;
    private javax.swing.JButton BotaoSugestao;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
