/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabteste;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author solange
 */
public class TelaMataMata8 extends javax.swing.JFrame {

    /**
     * Creates new form TelaMataMata
     */
    public TelaMataMata8() {
        initComponents();
        this.setSize(710, 430);
        this.setNome();
    }
    public TelaMataMata8(String a) {
        initComponents();
        this.setSize(710, 430);
        this.setNome(a);
    }
    

    public static String ultimosColocados1, ultimosColocados2, ultimosColocados3, ultimosColocados4;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ja4 = new javax.swing.JLabel();
        ja1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fa4 = new javax.swing.JTextField();
        fb2 = new javax.swing.JTextField();
        ja2 = new javax.swing.JLabel();
        ja6 = new javax.swing.JLabel();
        fa2 = new javax.swing.JTextField();
        fa3 = new javax.swing.JTextField();
        jb2 = new javax.swing.JLabel();
        ja3 = new javax.swing.JLabel();
        ja5 = new javax.swing.JLabel();
        jc2 = new javax.swing.JLabel();
        fa1 = new javax.swing.JTextField();
        fa7 = new javax.swing.JTextField();
        fa6 = new javax.swing.JTextField();
        fb1 = new javax.swing.JTextField();
        jb1 = new javax.swing.JLabel();
        j = new javax.swing.JLabel();
        fa5 = new javax.swing.JTextField();
        fa8 = new javax.swing.JTextField();
        ja7 = new javax.swing.JLabel();
        jc1 = new javax.swing.JLabel();
        ja8 = new javax.swing.JLabel();
        fc2 = new javax.swing.JTextField();
        fc1 = new javax.swing.JTextField();
        fb3 = new javax.swing.JTextField();
        jb3 = new javax.swing.JLabel();
        fb4 = new javax.swing.JTextField();
        jb4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ja4.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        ja4.setForeground(new java.awt.Color(255, 255, 255));
        ja4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(ja4);
        ja4.setBounds(10, 290, 80, 20);

        ja1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        ja1.setForeground(new java.awt.Color(255, 255, 255));
        ja1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(ja1);
        ja1.setBounds(0, 70, 90, 20);

        jLabel2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Confrontos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 20, 150, 30);

        fa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fa4ActionPerformed(evt);
            }
        });
        getContentPane().add(fa4);
        fa4.setBounds(90, 280, 40, 30);
        getContentPane().add(fb2);
        fb2.setBounds(190, 190, 40, 30);

        ja2.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        ja2.setForeground(new java.awt.Color(255, 255, 255));
        ja2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(ja2);
        ja2.setBounds(0, 110, 90, 20);

        ja6.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        ja6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ja6);
        ja6.setBounds(580, 110, 120, 20);
        getContentPane().add(fa2);
        fa2.setBounds(90, 100, 40, 30);
        getContentPane().add(fa3);
        fa3.setBounds(90, 240, 40, 30);

        jb2.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jb2.setForeground(new java.awt.Color(255, 255, 255));
        jb2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jb2);
        jb2.setBounds(90, 200, 100, 20);

        ja3.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        ja3.setForeground(new java.awt.Color(255, 255, 255));
        ja3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(ja3);
        ja3.setBounds(10, 250, 80, 20);

        ja5.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        ja5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ja5);
        ja5.setBounds(580, 70, 120, 20);

        jc2.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jc2.setForeground(new java.awt.Color(255, 255, 255));
        jc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jc2);
        jc2.setBounds(270, 230, 130, 20);
        getContentPane().add(fa1);
        fa1.setBounds(90, 60, 40, 30);
        getContentPane().add(fa7);
        fa7.setBounds(540, 250, 40, 30);

        fa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fa6ActionPerformed(evt);
            }
        });
        getContentPane().add(fa6);
        fa6.setBounds(540, 100, 40, 30);

        fb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb1ActionPerformed(evt);
            }
        });
        getContentPane().add(fb1);
        fb1.setBounds(190, 140, 40, 30);

        jb1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jb1.setForeground(new java.awt.Color(255, 255, 255));
        jb1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jb1);
        jb1.setBounds(90, 150, 100, 20);

        j.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        j.setForeground(new java.awt.Color(204, 204, 0));
        getContentPane().add(j);
        j.setBounds(230, 280, 220, 50);
        getContentPane().add(fa5);
        fa5.setBounds(540, 60, 40, 30);
        getContentPane().add(fa8);
        fa8.setBounds(540, 290, 40, 30);

        ja7.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        ja7.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ja7);
        ja7.setBounds(580, 260, 90, 20);

        jc1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jc1.setForeground(new java.awt.Color(255, 255, 255));
        jc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jc1);
        jc1.setBounds(270, 140, 120, 20);

        ja8.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        ja8.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ja8);
        ja8.setBounds(580, 300, 100, 20);
        getContentPane().add(fc2);
        fc2.setBounds(310, 200, 40, 30);
        getContentPane().add(fc1);
        fc1.setBounds(310, 160, 40, 30);
        getContentPane().add(fb3);
        fb3.setBounds(410, 140, 40, 30);

        jb3.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jb3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jb3);
        jb3.setBounds(450, 150, 120, 20);
        getContentPane().add(fb4);
        fb4.setBounds(410, 190, 40, 30);

        jb4.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jb4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jb4);
        jb4.setBounds(450, 200, 120, 20);

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 10, 100, 23);

        fundo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        fundo.setForeground(new java.awt.Color(255, 255, 255));
        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabteste/WhatsApp Image 2017-11-03 at 9.33.29 PM.jpeg"))); // NOI18N
        fundo.setText("jLabel1");
        getContentPane().add(fundo);
        fundo.setBounds(0, -10, 700, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fb1ActionPerformed

    private void fa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fa4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fa4ActionPerformed

    private void fa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fa6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fa6ActionPerformed
        private void setNome(String a) {      
            ja1.setText(a);
            Tela2.Participantes.remove(a);
            ja2.setText("BOT");
            Sorteio s = new Sorteio();
            s.Sortear();           
            ja3.setText(Tela2.Participantes.get(0));
            ja4.setText(Tela2.Participantes.get(1));
            ja5.setText(Tela2.Participantes.get(2));
            ja6.setText(Tela2.Participantes.get(3));
            ja7.setText(Tela2.Participantes.get(4));
            ja8.setText(Tela2.Participantes.get(5));        
        }
        private void setNome() {
            Sorteio s = new Sorteio();
            s.Sortear();
            ja1.setText(Tela2.Participantes.get(0));
            ja2.setText(Tela2.Participantes.get(1));
            ja3.setText(Tela2.Participantes.get(2));
            ja4.setText(Tela2.Participantes.get(3));
            ja5.setText(Tela2.Participantes.get(4));
            ja6.setText(Tela2.Participantes.get(5));
            ja7.setText(Tela2.Participantes.get(6));
            ja8.setText(Tela2.Participantes.get(7));      
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //----------------------OITAVAS DE FINAL ----------------------
        //part1
        if (Tela2.Participantes.size() == 7) {
            jb1.setText(ja1.getText());
        } else {
            if (!fa1.getText().equals("") && !fa2.getText().equals("")) {
                int a1 = Integer.parseInt(fa1.getText());
                int a2 = Integer.parseInt(fa2.getText());
                if (a1 > a2) {
                    jb2.setText(ja1.getText());
                } else if (a2 > a1) {
                    jb2.setText(ja2.getText());
                }
            }
        }
        
        

        //part2   
        if (!fa3.getText().equals("") && !fa4.getText().equals("")) {
            int a3 = Integer.parseInt(fa3.getText());
            int a4 = Integer.parseInt(fa4.getText());
            if (a3 > a4) {
                jb2.setText(ja3.getText());
            } else if (a4 > a3) {
                jb2.setText(ja4.getText());
            }
        }
        //part 3
        if (!fa5.getText().equals("") && !fa6.getText().equals("")) {
            int a5 = Integer.parseInt(fa5.getText());
            int a6 = Integer.parseInt(fa6.getText());
            if (a5 > a6) {
                jb3.setText(ja5.getText());
            } else if (a6 > a5) {
                jb3.setText(ja6.getText());
            }
        }
        //part4
        if (!fa7.getText().equals("") && !fa4.getText().equals("")) {
            int a7 = Integer.parseInt(fa3.getText());
            int a8 = Integer.parseInt(fa4.getText());
            if (a7 > a8) {
                jb4.setText(ja7.getText());
            } else if (a8 > a7) {
                jb4.setText(ja8.getText());
            }
        }
        //----------------------SEMI FINAIS----------------------
        //part1
        if (!fb1.getText().equals("") && !fb2.getText().equals("")) {
            int b1 = Integer.parseInt(fb1.getText());
            int b2 = Integer.parseInt(fb2.getText());
            if (b1 > b2) {
                jc1.setText(jb1.getText());
            } else if (b2 > b1) {
                jc1.setText(jb2.getText());
            }
        }

        //part2
        if (!fb3.getText().equals("") && !fb4.getText().equals("")) {
            int b3 = Integer.parseInt(fb3.getText());
            int b4 = Integer.parseInt(fb4.getText());
            if (b3 > b4) {
                jc2.setText(jb3.getText());
            } else if (b4 > b3) {
                jc2.setText(jb4.getText());
            }
        }
        //-------------------PILHA------------------------
        Pilha pilha = new Pilha();

        int p1 = Integer.parseInt(fa1.getText());
        int p2 = Integer.parseInt(fa2.getText());

        if (p1 < p2) {
            pilha.empilhar(ja1.getText());
        } else if (p2 < p1) {
            pilha.empilhar(ja2.getText());
        }

        int p3 = Integer.parseInt(fa3.getText());
        int p4 = Integer.parseInt(fa4.getText());

        if (p3 < p4) {
            pilha.empilhar(ja3.getText());
        } else if (p4 < p3) {
            pilha.empilhar(ja4.getText());
        }

        int p5 = Integer.parseInt(fa5.getText());
        int p6 = Integer.parseInt(fa6.getText());

        if (p5 < p6) {
            pilha.empilhar(ja5.getText());
        } else if (p6 < p5) {
            pilha.empilhar(ja6.getText());
        }
        
        int p7 = Integer.parseInt(fa7.getText());
        int p8 = Integer.parseInt(fa8.getText());
       
        if (p7 < p8) {
            pilha.empilhar(ja7.getText());
        } else if (p8 < p7) {
            pilha.empilhar(ja8.getText());
        }
       
        try {
            ultimosColocados1 = (String) pilha.desempilhar();
        } catch (PilhaVaziaException ex) {
            Logger.getLogger(TelaMataMata6.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ultimosColocados2 = (String) pilha.desempilhar();
        } catch (PilhaVaziaException ex) {
            Logger.getLogger(TelaMataMata6.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ultimosColocados3 = (String) pilha.desempilhar();
        } catch (PilhaVaziaException ex) {
            Logger.getLogger(TelaMataMata6.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ultimosColocados4 = (String) pilha.desempilhar();
        } catch (PilhaVaziaException ex) {
            Logger.getLogger(TelaMataMata6.class.getName()).log(Level.SEVERE, null, ex);
        }

        //----------------------FINAL----------------------
        if (!fc1.getText().equals("") && !fc2.getText().equals("")) {
            int c1 = Integer.parseInt(fc1.getText());
            int c2 = Integer.parseInt(fc2.getText());
            if (c1 > c2) {
                j.setText(jc1.getText());
                String caminhoArquivo1 = Tela2.diretorio;
                String txt = "O campeão do torneio foi: " + j.getText() + "\r\n  Ultimos Colocados - " 
                          + ultimosColocados1 + ",  " + ultimosColocados2 + ",  " + ultimosColocados3 + ",  " + ultimosColocados4;
                try {
                    //manipulação do arquivo
                    FileWriter fw = new FileWriter(caminhoArquivo1);
                    try (BufferedWriter fwriter = new BufferedWriter(fw)) {
                        fwriter.write(txt);
                    }
                } catch (IOException e) {

                }
            } else if (c2 > c1) {
                j.setText(jc2.getText());
                String caminhoArquivo1 = Tela2.diretorio;
                String txt = "O campeão do torneio foi: " + j.getText() + "\r\n  Ultimos Colocados - " 
                          + ultimosColocados1 + ",  " + ultimosColocados2 + ",  " + ultimosColocados3 + ",  " + ultimosColocados4;
                try {
                    //manipulação do arquivo
                    FileWriter fw = new FileWriter(caminhoArquivo1);
                    try (BufferedWriter fwriter = new BufferedWriter(fw)) {
                        fwriter.write(txt);
                    }
                } catch (IOException e) {

                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMataMata8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMataMata8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMataMata8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMataMata8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaMataMata8().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fa1;
    private javax.swing.JTextField fa2;
    private javax.swing.JTextField fa3;
    private javax.swing.JTextField fa4;
    private javax.swing.JTextField fa5;
    private javax.swing.JTextField fa6;
    private javax.swing.JTextField fa7;
    private javax.swing.JTextField fa8;
    private javax.swing.JTextField fb1;
    private javax.swing.JTextField fb2;
    private javax.swing.JTextField fb3;
    private javax.swing.JTextField fb4;
    private javax.swing.JTextField fc1;
    private javax.swing.JTextField fc2;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel j;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel ja1;
    private javax.swing.JLabel ja2;
    private javax.swing.JLabel ja3;
    private javax.swing.JLabel ja4;
    private javax.swing.JLabel ja5;
    private javax.swing.JLabel ja6;
    private javax.swing.JLabel ja7;
    private javax.swing.JLabel ja8;
    private javax.swing.JLabel jb1;
    private javax.swing.JLabel jb2;
    private javax.swing.JLabel jb3;
    private javax.swing.JLabel jb4;
    private javax.swing.JLabel jc1;
    private javax.swing.JLabel jc2;
    // End of variables declaration//GEN-END:variables
}
