/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabteste;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author guilu
 */
public class TelaMataMata16p2 extends javax.swing.JFrame {

    /**
     * Creates new form TelaMataMata16p2
     */
    public TelaMataMata16p2() {
        initComponents();
        this.setSize(500, 310);
        this.setNome();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        fa4 = new javax.swing.JTextField();
        fa3 = new javax.swing.JTextField();
        ja3 = new javax.swing.JLabel();
        fb1 = new javax.swing.JTextField();
        jb2 = new javax.swing.JLabel();
        fa2 = new javax.swing.JTextField();
        ja2 = new javax.swing.JLabel();
        fa1 = new javax.swing.JTextField();
        j = new javax.swing.JLabel();
        ja1 = new javax.swing.JLabel();
        fb2 = new javax.swing.JTextField();
        jb1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ja4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Semis e Final");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 370, 30);

        fa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fa4ActionPerformed(evt);
            }
        });
        getContentPane().add(fa4);
        fa4.setBounds(170, 220, 40, 30);
        getContentPane().add(fa3);
        fa3.setBounds(170, 190, 40, 30);

        ja3.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        ja3.setForeground(new java.awt.Color(255, 255, 255));
        ja3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(ja3);
        ja3.setBounds(20, 190, 150, 30);
        getContentPane().add(fb1);
        fb1.setBounds(410, 130, 40, 30);

        jb2.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jb2.setForeground(new java.awt.Color(255, 255, 255));
        jb2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jb2);
        jb2.setBounds(260, 160, 150, 30);

        fa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fa2ActionPerformed(evt);
            }
        });
        getContentPane().add(fa2);
        fa2.setBounds(170, 130, 40, 30);

        ja2.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        ja2.setForeground(new java.awt.Color(255, 255, 255));
        ja2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(ja2);
        ja2.setBounds(20, 130, 150, 30);
        getContentPane().add(fa1);
        fa1.setBounds(170, 100, 40, 30);

        j.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        j.setForeground(new java.awt.Color(255, 255, 51));
        j.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(j);
        j.setBounds(240, 220, 260, 70);

        ja1.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        ja1.setForeground(new java.awt.Color(255, 255, 255));
        ja1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(ja1);
        ja1.setBounds(20, 100, 150, 30);

        fb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb2ActionPerformed(evt);
            }
        });
        getContentPane().add(fb2);
        fb2.setBounds(410, 160, 40, 30);

        jb1.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jb1.setForeground(new java.awt.Color(255, 255, 255));
        jb1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jb1);
        jb1.setBounds(260, 130, 150, 30);

        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 10, 90, 40);

        ja4.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        ja4.setForeground(new java.awt.Color(255, 255, 255));
        ja4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(ja4);
        ja4.setBounds(20, 220, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabteste/WhatsApp Image 2017-09-12 at 23.25.53.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, -6, 500, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fa4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fa4ActionPerformed

    private void fa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fa2ActionPerformed

    private void fb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fb2ActionPerformed
  
    public void setNome() {
        ja1.setText(TelaMataMata16.classificados.get(0));
        ja2.setText(TelaMataMata16.classificados.get(1));
        ja3.setText(TelaMataMata16.classificados.get(2));
        ja4.setText(TelaMataMata16.classificados.get(3));
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        //-------------------------SEMI FINAIS----------------------
        //part1
        if (!fa1.getText().equals("") && !fa2.getText().equals("")) {
            int a1 = Integer.parseInt(fa1.getText());
            int a2 = Integer.parseInt(fa2.getText());
            if (a1 > a2) {
                jb1.setText(ja1.getText());
            } else if (a2 > a1) {
                jb1.setText(ja2.getText());
            }
        }

        //part2
        if (!fa3.getText().equals("") && !fa4.getText().equals("")) {
            int a3 = Integer.parseInt(fa3.getText());
            int a4 = Integer.parseInt(fa4.getText());
            if (a3 > a4) {
                jb2.setText(ja3.getText());
            } else if (a4 > a3) {
                jb2.setText(ja4.getText());
            }
        }
        //--------------------------FINAL----------------------------
        if (!fb1.getText().equals("") && !fb2.getText().equals("")) {
            int b1 = Integer.parseInt(fb1.getText());
            int b2 = Integer.parseInt(fb2.getText());
            if (b1 > b2) {
                j.setText(jb1.getText());
                String caminhoArquivo1 = Tela2.diretorio;
                String txt = "O campeão do torneio foi: " + j.getText() + "\r\n  Ultimos Colocados - "
                        + TelaMataMata16.ultimosColocados1 + ",  " + TelaMataMata16.ultimosColocados2 + ",  " + TelaMataMata16.ultimosColocados3 + ",  " + TelaMataMata16.ultimosColocados4
                        + TelaMataMata16.ultimosColocados5 + ",  " + TelaMataMata16.ultimosColocados6 + ",  " + TelaMataMata16.ultimosColocados7 + ",  " + TelaMataMata16.ultimosColocados8;
                try {
                    //manipulação do arquivo
                    FileWriter fw = new FileWriter(caminhoArquivo1);
                    BufferedWriter fwriter = new BufferedWriter(fw);
                    fwriter.write(txt);
                    fwriter.close();
                } catch (IOException e) {

                }
            } else if (b2 > b1) {
                j.setText(jb2.getText());
                String caminhoArquivo1 = Tela2.diretorio;
                String txt = "O campeão do torneio foi: " + j.getText() + "\r\n  Ultimos Colocados - "
                        + TelaMataMata16.ultimosColocados1 + ",  " + TelaMataMata16.ultimosColocados2 + ",  " + TelaMataMata16.ultimosColocados3 + ",  " + TelaMataMata16.ultimosColocados4
                       +  TelaMataMata16.ultimosColocados5 + ",  " + TelaMataMata16.ultimosColocados6 + ",  " + TelaMataMata16.ultimosColocados7 + ",  " + TelaMataMata16.ultimosColocados8;
                try {
                    //manipulação do arquivo
                    FileWriter fw = new FileWriter(caminhoArquivo1);
                    BufferedWriter fwriter = new BufferedWriter(fw);
                    fwriter.write(txt);
                    fwriter.close();
                } catch (IOException e) {

                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMataMata16p2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMataMata16p2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMataMata16p2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMataMata16p2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaMataMata16p2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fa1;
    private javax.swing.JTextField fa2;
    private javax.swing.JTextField fa3;
    private javax.swing.JTextField fa4;
    private javax.swing.JTextField fb1;
    private javax.swing.JTextField fb2;
    private javax.swing.JLabel j;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel ja1;
    private javax.swing.JLabel ja2;
    private javax.swing.JLabel ja3;
    private javax.swing.JLabel ja4;
    private javax.swing.JLabel jb1;
    private javax.swing.JLabel jb2;
    // End of variables declaration//GEN-END:variables
}
